In [1]:
import json 
import pandas as pd 
import numpy as np

In [4]:
df_database = pd.read_json('../data/airlines-1558527599826.json', lines=True)
df_database.head()

,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,filter_level,lang,timestamp_ms,retweeted_status,extended_tweet,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,delete
0,2019-05-22 12:20:00+00:00,1.131173e+18,1.131173e+18,La ruta de easyJet entre Londres y Menorca tra...,"[0, 113]","<a href=""https://about.twitter.com/products/tw...",0.0,NaN,NaN,NaN,...,low,es,2019-05-22 12:20:00.406,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-05-22 12:20:01+00:00,1.131173e+18,1.131173e+18,RT @bttr_as1: @goody_tracy Here’s a list of so...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",0.0,NaN,NaN,NaN,...,low,en,2019-05-22 12:20:01.645,{'created_at': 'Tue May 21 19:43:11 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-05-22 12:20:02+00:00,1.131173e+18,1.131173e+18,@British_Airways,NaN,"<a href=""http://twitter.com/download/android"" ...",0.0,1.131033e+18,1.131033e+18,394376606.0,...,low,und,2019-05-22 12:20:02.560,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-05-22 12:20:12+00:00,1.131173e+18,1.131173e+18,RT @TheRaceRadio: Nice change by @AmericanAir....,NaN,"<a href=""http://twitter.com/download/android"" ...",0.0,NaN,NaN,NaN,...,low,en,2019-05-22 12:20:12.449,{'created_at': 'Wed May 22 02:53:26 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-05-22 12:20:28+00:00,1.131173e+18,1.131173e+18,RT @sandeeprrao1991: BREAKING:-\nKLM to fly 3x...,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0.0,NaN,NaN,NaN,...,low,en,2019-05-22 12:20:28.237,{'created_at': 'Wed May 22 12:10:24 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_datas = df_database.dropna(subset = ["user"]).reset_index()
df_datas

,index,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,...,filter_level,lang,timestamp_ms,retweeted_status,extended_tweet,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,delete
0,0,2019-05-22 12:20:00+00:00,1.131173e+18,1.131173e+18,La ruta de easyJet entre Londres y Menorca tra...,"[0, 113]","<a href=""https://about.twitter.com/products/tw...",0.0,NaN,NaN,...,low,es,2019-05-22 12:20:00.406,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2019-05-22 12:20:01+00:00,1.131173e+18,1.131173e+18,RT @bttr_as1: @goody_tracy Here’s a list of so...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",0.0,NaN,NaN,...,low,en,2019-05-22 12:20:01.645,{'created_at': 'Tue May 21 19:43:11 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2019-05-22 12:20:02+00:00,1.131173e+18,1.131173e+18,@British_Airways,NaN,"<a href=""http://twitter.com/download/android"" ...",0.0,1.131033e+18,1.131033e+18,...,low,und,2019-05-22 12:20:02.560,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2019-05-22 12:20:12+00:00,1.131173e+18,1.131173e+18,RT @TheRaceRadio: Nice change by @AmericanAir....,NaN,"<a href=""http://twitter.com/download/android"" ...",0.0,NaN,NaN,...,low,en,2019-05-22 12:20:12.449,{'created_at': 'Wed May 22 02:53:26 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2019-05-22 12:20:28+00:00,1.131173e+18,1.131173e+18,RT @sandeeprrao1991: BREAKING:-\nKLM to fly 3x...,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0.0,NaN,NaN,...,low,en,2019-05-22 12:20:28.237,{'created_at': 'Wed May 22 12:10:24 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14382,14384,2019-05-23 11:42:26+00:00,1.131526e+18,1.131526e+18,@yvettetravel were you invited to attend this?,NaN,"<a href=""http://twitter.com/download/iphone"" r...",0.0,NaN,NaN,...,low,en,2019-05-23 11:42:26.066,NaN,NaN,1.131507e+18,1.131507e+18,{'created_at': 'Thu May 23 10:28:34 +0000 2019...,"{'url': 'https://t.co/iLnuh7ejub', 'expanded':...",NaN
14383,14385,2019-05-23 11:42:27+00:00,1.131526e+18,1.131526e+18,RT @RoyalFamily: The Queen sees how the @Briti...,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",0.0,NaN,NaN,...,low,en,2019-05-23 11:42:27.109,{'created_at': 'Thu May 23 11:13:08 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
14384,14386,2019-05-23 11:42:27+00:00,1.131526e+18,1.131526e+18,@RoyalSpectator @British_Airways She looks AMA...,"[33, 60]","<a href=""http://twitter.com"" rel=""nofollow"">Tw...",0.0,1.131512e+18,1.131512e+18,...,low,en,2019-05-23 11:42:27.469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14385,14387,2019-05-23 11:42:35+00:00,1.131526e+18,1.131526e+18,@maj_fox @British_Airways Should happen more o...,"[26, 94]","<a href=""http://twitter.com/download/android"" ...",0.0,1.131484e+18,1.131484e+18,...,low,en,2019-05-23 11:42:35.858,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14386,14388,2019-05-23 11:42:44+00:00,1.131526e+18,1.131526e+18,@British_Airways delayed 5hrs on flight BA0103...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",1.0,NaN,NaN,...,low,en,2019-05-23 11:42:44.440,NaN,{'full_text': '@British_Airways delayed 5hrs o...,NaN,NaN,NaN,NaN,NaN

In [248]:
#Counting how many tweets made by KLM,Bri (including posting+ replying to other):
count_made_klm = 0
count_made_bri = 0
for d in df_datas.user:
    if d.get("id_str") == "56377143":
        count_made_klm +=1
    if d.get("id_str") == "18332190":
        count_made_bri +=1
        
print(count_made_klm,count_made_bri)

87 343

In [280]:
#Counting how many tweets mention KLM, Bri:
count_ment_klm = 0
count_ment_bri = 0

for d in df_datas.entities:
    for i in d.get("user_mentions"):
        if i.get("id_str") == "56377143":
            count_ment_klm +=1
        if i.get("id_str") == "18332190":
            count_ment_bri +=1
            
print(count_ment_klm,count_ment_bri)

334 1770

In [10]:
#Extract only tweets made by KLM (including posting +replying to other):
test = df_datas.copy()

ind = []
for index, row in df_datas.iterrows():
    if row['user']['id_str'] == '56377143':
        ind.append(index)
klm_tweet = df_datas.iloc[ind]
klm_tweet.reset_index(inplace=True)
klm_tweet

,level_0,index,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,...,filter_level,lang,timestamp_ms,retweeted_status,extended_tweet,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,delete
0,36,36,2019-05-22 12:23:03+00:00,1.131174e+18,1.131174e+18,@Pelusitaaaa1 Hoi! Enkel KLM/Air France-vluch...,"[14, 140]","<a href=""http://www.salesforce.com"" rel=""nofol...",1.0,1.131171e+18,...,low,nl,2019-05-22 12:23:03.108,NaN,{'full_text': '@Pelusitaaaa1 Hoi! Enkel KLM/A...,NaN,NaN,NaN,NaN,NaN
1,635,635,2019-05-22 13:09:16+00:00,1.131185e+18,1.131185e+18,@Pelusitaaaa1 We helpen je graag. Kan je ons e...,"[14, 107]","<a href=""http://www.salesforce.com"" rel=""nofol...",0.0,1.131183e+18,...,low,nl,2019-05-22 13:09:16.877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,785,785,2019-05-22 13:20:05+00:00,1.131188e+18,1.131188e+18,@addblackman We understand that you would pref...,"[13, 140]","<a href=""http://www.salesforce.com"" rel=""nofol...",1.0,1.131182e+18,...,low,en,2019-05-22 13:20:05.252,NaN,{'full_text': '@addblackman We understand that...,NaN,NaN,NaN,NaN,NaN
3,788,788,2019-05-22 13:20:17+00:00,1.131188e+18,1.131188e+18,@CarlosMosig Con el fin de evitar errores noso...,"[13, 140]","<a href=""http://www.salesforce.com"" rel=""nofol...",1.0,1.131183e+18,...,low,es,2019-05-22 13:20:17.115,NaN,{'full_text': '@CarlosMosig Con el fin de evit...,NaN,NaN,NaN,NaN,NaN
4,791,791,2019-05-22 13:20:31+00:00,1.131188e+18,1.131188e+18,@addblackman We do understand that some passen...,"[13, 140]","<a href=""http://www.salesforce.com"" rel=""nofol...",1.0,1.131182e+18,...,low,en,2019-05-22 13:20:31.611,NaN,{'full_text': '@addblackman We do understand t...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,13753,13755,2019-05-23 11:05:39+00:00,1.131517e+18,1.131517e+18,@JonathanGunson We'd like to check this for yo...,"[16, 140]","<a href=""http://www.salesforce.com"" rel=""nofol...",1.0,1.131512e+18,...,low,en,2019-05-23 11:05:39.431,NaN,{'full_text': '@JonathanGunson We'd like to ch...,NaN,NaN,NaN,NaN,NaN
83,13916,13918,2019-05-23 11:15:59+00:00,1.131519e+18,1.131519e+18,@JonathanGunson We have replied to your DM!,"[16, 43]","<a href=""http://www.salesforce.com"" rel=""nofol...",0.0,1.131517e+18,...,low,en,2019-05-23 11:15:59.844,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,13990,13992,2019-05-23 11:19:29+00:00,1.131520e+18,1.131520e+18,"@alexVonline Hoi, vervelend om te lezen dat je...","[13, 140]","<a href=""http://www.salesforce.com"" rel=""nofol...",1.0,1.131518e+18,...,low,nl,2019-05-23 11:19:29.027,NaN,"{'full_text': '@alexVonline Hoi, vervelend om ...",NaN,NaN,NaN,NaN,NaN
85,14030,14032,2019-05-23 11:21:36+00:00,1.131521e+18,1.131521e+18,@djmogul We highly advise against sharing your...,"[9, 140]","<a href=""http://www.salesforce.com"" rel=""nofol...",1.0,1.131519e+18,...,low,en,2019-05-23 11:21:36.721,NaN,{'full_text': '@djmogul We highly advise again...,NaN,NaN,NaN,NaN,NaN
86,14319,14321,2019-05-23 11:37:25+00:00,1.131525e+18,1.131525e+18,"@alexVonline DM gezien, we hebben je inmiddels...","[13, 139]","<a href=""http://www.salesforce.com"" rel=""nofol...",0.0,1.131520e+18,...,low,nl,2019-05-23 11:37:25.285,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Extract only tweets mention KLM (@KLM etc...):
test2 = df_datas.copy()
ind2 = []
for index, row in df_datas.iterrows():
    if "@KLM" in row['text']:
        ind2.append(index)
klm_tweet_men = df_datas.loc[ind2]
klm_tweet_men

,index,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,...,filter_level,lang,timestamp_ms,retweeted_status,extended_tweet,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,delete
54,54,2019-05-22 12:24:26+00:00,1.131174e+18,1.131174e+18,RT @McWhirterAlex: .@KLM will fly Amsterdam-Ba...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",0.0,NaN,NaN,...,low,en,2019-05-22 12:24:26.336,{'created_at': 'Wed May 22 11:49:14 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
55,55,2019-05-22 12:24:31+00:00,1.131174e+18,1.131174e+18,RT @Vinamralongani: @KLM to launch thrice week...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",0.0,NaN,NaN,...,low,en,2019-05-22 12:24:31.580,{'created_at': 'Wed May 22 11:52:42 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
92,92,2019-05-22 12:27:15+00:00,1.131175e+18,1.131175e+18,@wolfmandanny @KLM Thanks Dan,"[19, 29]","<a href=""http://twitter.com/download/iphone"" r...",0.0,1.131164e+18,1.131164e+18,...,low,en,2019-05-22 12:27:15.180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,173,2019-05-22 12:35:00+00:00,1.131177e+18,1.131177e+18,Waar @KLM de slots vandaan haalt is (nog) niet...,NaN,"<a href=""http://twitter.com/#!/download/ipad"" ...",0.0,NaN,NaN,...,low,nl,2019-05-22 12:35:00.067,NaN,NaN,1.131160e+18,1.131160e+18,{'created_at': 'Wed May 22 11:28:04 +0000 2019...,"{'url': 'https://t.co/GwwWYOYj61', 'expanded':...",NaN
204,204,2019-05-22 12:37:29+00:00,1.131177e+18,1.131177e+18,@KLM Aviation releases about 3% of human carbo...,"[5, 124]","<a href=""https://mobile.twitter.com"" rel=""nofo...",0.0,1.111660e+18,1.111660e+18,...,low,en,2019-05-22 12:37:29.913,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14260,14262,2019-05-23 11:34:10+00:00,1.131524e+18,1.131524e+18,RT @FlightGlobal: .@KLM moves to replace @jeta...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",0.0,NaN,NaN,...,low,en,2019-05-23 11:34:10.254,{'created_at': 'Thu May 23 11:30:18 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
14262,14264,2019-05-23 11:34:15+00:00,1.131524e+18,1.131524e+18,@markbrouwer2010 @KLM Ga toch fietsen!,"[22, 38]","<a href=""http://twitter.com/download/iphone"" r...",0.0,1.131292e+18,1.131292e+18,...,low,nl,2019-05-23 11:34:15.962,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14293,14295,2019-05-23 11:36:09+00:00,1.131524e+18,1.131524e+18,@RedGelderland @lies92416763 @SchipholWatch @s...,"[73, 140]","<a href=""http://twitter.com"" rel=""nofollow"">Tw...",1.0,1.131518e+18,1.131518e+18,...,low,nl,2019-05-23 11:36:09.251,NaN,{'full_text': '@RedGelderland @lies92416763 @S...,NaN,NaN,NaN,NaN,NaN
14325,14327,2019-05-23 11:37:55+00:00,1.131525e+18,1.131525e+18,@PlantTeaching @mmjulkowska @KLM I second comp...,"[33, 140]","<a href=""http://twitter.com/download/iphone"" r...",1.0,1.131513e+18,1.131513e+18,...,low,en,2019-05-23 11:37:55.223,NaN,{'full_text': '@PlantTeaching @mmjulkowska @KL...,NaN,NaN,NaN,NaN,NaN
14342,14344,2019-05-23 11:39:01+00:00,1.131525e+18,1.131525e+18,@KLM Wat is jullie vertragingspercentage per m...,"[5, 51]","<a href=""http://twitter.com/download/iphone"" r...",0.0,1.131525e+18,1.131525e+18,...,low,nl,2019-05-23 11:39:01.337,NaN,NaN,NaN,NaN,NaN,NaN,NaN